#!/usr/bin/env ansible-playbook
- hosts: localhost
  become: yes
  connection: local
  roles:
    - setup/node-controller
    - networking/internal
    - networking/gateway
    - networking/hostname
    - services/dns
    - services/dhcp
    - services/ntp

